name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.actor }}"
          echo "${{ github.event_name }}"
          echo "${{ runner.name }}"
